<html lang="es">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
    <style>
    @font-face {
    font-family: 'Conv_blue highway bd';
    src: url('web/css/blue highway bd.eot');
    src: local('☺'), url('web/css/blue highway bd.woff') format('woff'), url('web/css/blue highway bd.ttf') format('truetype'), url('web/css/blue highway bd.svg') format('svg');
    font-weight: normal;
    font-style: normal;
}
@font-face {
    font-family: 'Conv_blue highway cd';
    src: url('web/css/blue highway cd.eot');
    src: local('☺'), url('web/css/blue highway cd.woff') format('woff'), url('web/css/blue highway cd.ttf') format('truetype'), url('web/css/blue highway cd.svg') format('svg');
    font-weight: normal;
    font-style: normal;
}
@font-face {
    font-family: 'Conv_blue highway d';
    src: url('web/css/blue highway d.eot');
    src: local('☺'), url('web/css/blue highway d.woff') format('woff'), url('web/css/blue highway d.ttf') format('truetype'), url('web/css/blue highway d.svg') format('svg');
    font-weight: normal;
    font-style: normal;
}
@font-face {
    font-family: 'Conv_blue highway linocut';
    src: url('web/css/blue highway linocut.eot');
    src: local('☺'), url('web/css/blue highway linocut.woff') format('woff'), url('web/css/blue highway linocut.ttf') format('truetype'), url('web/css/blue highway linocut.svg') format('svg');
    font-weight: normal;
    font-style: normal;
}
/** Generated by FG **/
@font-face {
    font-family: 'Conv_blue highway rg';
    src: url('web/css/blue highway rg.eot');
    src: local('☺'), url('web/css/blue highway rg.woff') format('woff'), url('web/css/blue highway rg.ttf') format('truetype'), url('web/css/blue highway rg.svg') format('svg');
    font-weight: normal;
    font-style: normal;
}
/** Generated by FG **/
/*@font-face {
    font-family: 'Yantramanav';
    src: url('LetterGothicStd.eot');
    src: local('☺'), url('LetterGothicStd.woff') format('woff'), url('LetterGothicStd.ttf') format('truetype'), url('LetterGothicStd.svg') format('svg');
    font-weight: normal;
    font-style: normal;
}*/
    body {
  margin: 0;
  padding: 0;
/*  Background fallback in case of IE8 & down, or in case video doens't load, such as with slower connections  */
  background: #333;
  background-attachment: fixed;
  background-size: cover;
  font-family: 'Conv_blue highway bd' !important; 
}

/* The only rule that matters */
#video-background {
/*  making the video fullscreen  */
  position: fixed;
  right: 0; 
  bottom: 0;
  min-width: 100%; 
  min-height: 100%;
  width: auto; 
  height: auto;
  z-index: -100;
}

/* These just style the content */
article {
/*  just a fancy border  */
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
 /* border: 10px solid rgba(255, 255, 255, 0.5);*/
  margin: 10px;
}

h1 {
  position: absolute;
  top: 85%;
  width: 100%;
  letter-spacing: 3px;
  color: #fff;
  text-align: center;
    z-index: 200;
    font-family: 'Conv_blue highway linocut' !important; 
}

h1 span {
  font-family: sans-serif;
  letter-spacing: 0;
  font-weight: 300;
  font-size: 16px;
  line-height: 24px;
  z-index: 200;
}

h1 span a {
  color: #fff;
  font-size: 1.5em;
  font-family: 'Conv_blue highway d' !important; 
}
@media (max-width: 768px){
h1 span a {font-size: 1.0em !important;}
.text-left{
    float: left;
    margin-left: 30% !important;;
}
.text-right{
    float: right;
    margin-right: 30% !important;;
}
}
img{
    z-index: 200;
    position: absolute;
}
article span a{
   /* margin-right: 10%;*/
}
.text-left{
    float: left;
    margin-left: 40%;
}
.text-right{
    float: right;
    margin-right: 40%;
}
    </style>
    <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
        <script  src="web/js/jquery.vimelar.min.js"></script>
    <script>
$('document').ready(function() {
    var options = {
        videoId: '254724445',
        parameters: {
            autopause: 1,
            autoplay: 1,
            badge: 1,
            byline: 1,
            color: '000',
            loop: 1,
            player_id: 'demo',
            portrait: 1,
            title: 1
        }
    };
    $('#wrapper').vimelar(options);

});
</script>
</head>
<body>
<div id="wrapper"></div>
    <article>
        <img src="web/images/logo.png">
  <h1><span><a class="text-left" href="web/index.php" >Spanish </a><a class="text-right" href="web/index.php"> English</a></span></h1>
</article>
</body>
</html>